version: '3'
services:
  openvas:
      restart: always
      image: myoung34/openvas
      hostname: openvas
      ports:
        - 4000:4000
      volumes:
        - ./data/openvas:/var/lib/openvas/mgr/
      environment:
        - OV_PASSWORD=securepassword41
      labels:
         deck-chores.dump.command: sh -c "greenbone-nvt-sync; openvasmd --rebuild --progress"
         deck-chores.dump.interval: daily
